local deserialize = require("lua.dbus-lua.deserialize")
local wire = require("lua.dbus-lua.wire")

describe("deserialize", function()
	describe("decode_uint32", function()
		it("basic number", function()
			local serialized = wire.encode_uint32(123456789)
			local n = deserialize.decode_uint32(serialized)
			assert.equals(123456789, n)
		end)
	end)

	describe("decode_string", function()
		it("basic string", function()
			local serialized = wire.encode_string("hello")
			local deserialized, bytes_read = deserialize.decode_string(serialized)

			assert.equals("hello", deserialized)
			assert.equals(10, bytes_read)
		end)
	end)
end)
